title: Hi, I am Ishan 👋
author: Ishan Sai Vepa
#color: "#2B546B"
color: "#FFFFFF"
description: |
  I have an avid interest in technology and computer science, but also pursue creative passions such 
  as video production and music. I have produced documentaries, and am a jazz saxophonist 
  musician. I am currently pursuing a Bachelor of Science in Computer Science at the
  <a href="https://www.gatech.edu/" target="_blank"> Georgia Institute of Technology</a> with a 
  concentration in Human-Computer Interaction.  
  I am also big soccer fan and an avid Manchester United supporter.
domain: ishanvepa.com
twitter: vepaishan
#mastodon: macaw.social/@gerard
sass:
    sass_dir: assets/_sass
    style: compressed
include: [".well-known"]

plugins:
  - jekyll-redirect-from
