title: Hi, I am Ishan 👋
author: Ishan Sai Vepa
color: "#2B546B"
description: |
  I have an avid interest in technology and computer science, but also pursue creative passions such 
  as video production and music. I have produced multiple documentaries and worked on community impact 
  musician. I'm specially interested in Machine Learning Infrastructure and Data Engineering. 
  I currently attend <a href="https://www.gatech.edu/" target="_blank">the Georgia Institute of Technology</a>. 
  I am an avid Manchester United fan, take pictures .
domain: ishanvepa.com
twitter: vepaishan
#mastodon: macaw.social/@gerard
sass:
    sass_dir: assets/_sass
    style: compressed
include: [".well-known"]

plugins:
  - jekyll-redirect-from
